export { default as Dashboard } from './Dashboard';
export { default as Onboarding } from './Onboarding';
export { default as Clinics } from './Clinics';
export { default as Hospitals } from './Hospitals';
export { default as Doctors } from './Doctors';
export { default as Services } from './Services';
export { default as Staff } from './Staff';
export { default as Bookings } from './Bookings';
export { default as Consultations } from './Consultations';
export { default as Payments } from './Payments';
export { Consultations as _consultations_placeholder, SettingsPage as SettingsPlaceholder } from './PlaceholderPages';
export { default as Settings } from './Settings';